[WIP][jsk_fetch_startup] add rossetip with
knorth55/jsk_robot pull request #228
Opened 2022-05-17 17:41 UTC by sktometometo

明示的にROS_IPを特定のネットワークインターフェースに設定するようにしました。

これにより、config.bash内の環境変数を切り替えてsupervisorのジョブを再起動するのみで、fetch1075のアクセスポイントに通信しているLaptopとROSTCPの通信を行うことができます。(このときは133側のPCとの通信はできない)

2022-05-18 17:40 UTC, 708yamaguchi commented
NETWORK_DEFAULT_WIFI_INTERFACE
NETWORK_DEFAULT_ROS_INTERFACE
というのは、それぞれどういう意味でしょうか。場合によっては同じインターフェース名が割り当てられても良い？
（追記: イーサの場合とかアクセスポイントモードの場合も考慮されてるということ？）
config.bashに説明があると良いと思います

またwlan0とwlan1は、どちらがアクセスポイントモードでどちらがsanshiroにつなぐのか、何らかの設定で固定できているのでしょうか

2022-05-18 18:43 UTC, sktometometo commented
`NETWORK_DEFAULT_WIFI_INTERFACE`: ネットワーク監視スクリプトでpingを送ったりip down したりするWANに接続されているはずのwifiデバイス
`NETWORK_DEFAULT_ROS_INTERFACE`: supervisorの各ジョブ実行時に rossetip <interface名> でROS_IPを設定するネットワークインターフェース

`wlan0` と `wlan1` があったときにどちらがWANに接続されてどちらがHotspotになっているかは NetworkManager のプロファイルで設定されています。
今は `nmtui` で手動で編集している。

2022-05-18 22:29 UTC, 708yamaguchi requested changes
config.bashにコメントを書いてほしいのと、以下にあるようにこれまでのPRも含めてjsk-ros-pkgにもプルリクエストを出していきましょう
https://github.com/knorth55/jsk_robot/issues/210

2022-05-20 04:43 UTC, 708yamaguchi commented
Thank you for your documentation.

Looks very nice to me.

2022-05-20 04:43 UTC, 708yamaguchi approved these changes

2022-05-20 04:43 UTC, merged

2022-05-26 06:19 UTC, knorth55 commented
@sktometometo ちょっと見ない間にFetchのネットワーク設定がぐちゃぐちゃになっています．
方針としてはどうなってるんでしょうか？
わからないんだけど，/var/lib/robot/config.bashの中にif文を書くか，fetchに外にいくようのsupervisorのconfを書くとか，何かしら解決策がある気がします．
ちょっとjsk_robotにcommitされていない変更があるのでjsk_robotにもどしますが，jsk_robotのほうになんでアクセスポイントのほうがあるんだ，という気持ちがある．
デフォルトは133につなぐようにしてください．そうじゃないとROSで外から繋げられない．
アクセスポイントの話はもう少しちゃんとやってください．
そしてFetch1075とFetch15で同じように変更していってください．

2022-05-26 06:22 UTC, knorth55 commented
もっと連絡をとって相談して変更してくれ〜