update config/config.bash to support fetch15 and fetch1075
knorth55/jsk_robot pull request #242
Opened 2022-05-26 06:51 UTC by knorth55

update config/config.bash to support fetch15 and fetch1075

2022-05-26 06:55 UTC, sktometometo approved these changes

2022-05-26 08:15 UTC, 708yamaguchi commented
I have 2 questions.

1
How do we use `config_outside.bash`?
We manually do 
- `sudo supervisorctl stop jsk-fetch-startup`
- load `config_outside.bash`
- roslaunch jsk_fetch_startup fetch_bringup.launch ...`
?

2
fetch15 has only wlan0 but fetch1075 has wlan0 and wlan1
What is the difference?
It would be better to write the usage of each interace and how to set them to README.md.

2022-05-26 08:39 UTC, sktometometo commented
@knorth55 said he woud add supervisor jobs with config_outside.bash instead of config.bash. So i thinks this PR is stll uncomplete.

Current Wi-Fi interfaces of Fetch are
- for Henzel
  + `wlan0`: Wi-Fi client to sanshiro
- for Gretel
  + `wlan0`: Wi-Fi AP (SSID: `fetch1075`)
  + `wlan1`: Wi-Fi client to sanshiro
Each configuration are managed by NetworkManager. Description of network profiles are now on README.md.

2022-05-26 08:42 UTC, sktometometo commented
Currently we do not need to take care for each Wi-Fi Interface if you use Fetch from `sanshiro` network. I'll write network configuration deploying system and write description of each interfaces in that time.

2022-05-26 08:46 UTC, 708yamaguchi commented
> @knorth55 said he woud add supervisor jobs with config_outside.bash instead of config.bash. So i thinks this PR is stll uncomplete.

OK, I see. I think it's good solution.

> Each configuration are managed by NetworkManager. Description of network profiles are now on README.md.

Sorry, I cannot find all of interface description in https://github.com/knorth55/jsk_robot/tree/fetch15/jsk_fetch_robot/jsk_fetch_startup#network-configuration .
But it's OK if you write the descirption later.

> I'll write network configuration deploying system and write description of each interfaces in that time.

2022-05-26 08:55 UTC, sktometometo commented
There are no desciprtion of network interface. There are descriptions of network profiles.https://github.com/knorth55/jsk_robot/tree/fetch15/jsk_fetch_robot/jsk_fetch_startup#default-connection-profiles

2022-05-26 09:14 UTC, 708yamaguchi commented
> There are no desciprtion of network interface. There are descriptions of network

Yes, so please add description.

2022-05-26 11:07 UTC, knorth55 commented
config_outside.bash is for outside of 73b2 room.
I think its good to have supervisor job for outside and load config_outside.bash in it.

2022-05-26 15:18 UTC, knorth55 commented
@sktometometo @708yamaguchi 色々supervisorのジョブをマージしました．
結果この３つだけ自分で立てれば外の設定が読み込まれるようになっていると思います．
- robot-outside
- jsk-fetch-startup-outside
- jsk-network-monitor-outside

2022-05-26 15:24 UTC, knorth55 commented
Supervisorの画面です．
一応残していますが，大体がjsk-fetch-startup.confのfetch_bringup.launchに集約されました．

![Screenshot from 2022-05-27 00-14-17](https://user-images.githubusercontent.com/9300063/170520117-40d49002-adb0-4093-ba85-2938c7516927.png)

2022-05-26 22:13 UTC, 708yamaguchi commented
@knorth55 
ありがとうございます。
ログをとること自体が目的のjob以外は、jsk-fetch-startupにマージしてしまっても良さそうですね

今回マージしたjob（jsk-app-chooserなど）をsupervisorの画面に残しているということですが、個人的には紛らわしいので消してしまっても良いように思いました。

2022-05-27 00:48 UTC, sktometometo requested changes

2022-05-27 00:48 UTC, sktometometo commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <arg name="launch_edgetpu_human_pose_estimator" default="true" />
panorama 画像を使いたい場合は /home/fetch/ros/catkin_ws/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch のこのあたりを編集する使用方法をそうていされていますか?
coral_usbを利用した認識システムは、たまにパノラマ画像使いたいときにFetchを使っているので、立ち上げ直ししなくても切り替えられるいままでのシステムが嬉しいです。

2022-05-27 00:48 UTC, sktometometo commented on jsk_fetch_robot/jsk_fetch_startup/config/install_supervisor.sh
```suggestion
sudo supervisorctl reread
```

今回のPRと直接関係ないのですが、 supervisord は conf を置き換えただけでは設定が反映されないので、installスクリプトで読み込み直しまで行いたいです。`update` (各プロセスがrestartする) と `reread` (実行中のプロセスはrestartしない) のどちらがいいかは議論の余地がありそうですが、実行直後の挙動は `reread` だと現在と変わらないため `reread` のほうがいいかなと思っています。実際に実行されているプロセスへ反映させるには `restart` が必要になります。

2022-05-27 01:07 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <arg name="launch_edgetpu_human_pose_estimator" default="true" />
今ままでのconfも残してるけどダメかな？
jsk_robotのbranchを切り替えることで対応できないかな
個人的には全て1つのlaunchに集約される冪だと思っているので（集約されてない奴らはlogに結構な頻度で書き込みするやつら）、今の感じでいい解決策を探したい

2022-05-27 01:08 UTC, knorth55 commented
confを残しているのは別々に起動したい人がいるかな、と思っているからです
どうだろう

2022-05-27 01:10 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <arg name="launch_edgetpu_human_pose_estimator" default="true" />
ちなみにcoralだけならcoralは切り替え機能を持ってるんだけどそっちを使うっていうのもあり
edgetpu_managerだったかな

2022-05-27 01:10 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <arg name="launch_edgetpu_human_pose_estimator" default="true" />
https://github.com/jsk-ros-pkg/coral_usb_ros/blob/master/node_scripts/edgetpu_node_manager.py

2022-05-27 01:11 UTC, 708yamaguchi commented
> confを残しているのは別々に起動したい人がいるかな、と思っているからです
どうだろう

なるほど、そういう意図があったんですね。
それなら残しておいたほうが良いと思います。

2022-05-27 01:16 UTC, knorth55 commented
supervisorとかの話って色々議論していると思います
でその中でlaunchをまとめていくことは岡田先生との間で共通の見解として合意が取れています
なので今後はそういう方針でできるだけいこうと思います

dstatはlogを他のところに出力すればマージできます
log-wifiはroot権限が必要っぽいので、そこを解決すればマージできます
coralについてはマージできるようになったのですがハードウェア的な制約で切り替えが必要です
切り替えのやり方としてrosserviceで切り替えられるようにしているので、そっちを使うようにしますか？

2022-05-27 01:34 UTC, sktometometo commented
> 切り替えのやり方としてrosserviceで切り替えられるようにしているので、そっちを使うようにしますか？

どういう方法でしょうか?

2022-05-27 02:06 UTC, knorth55 commented
https://github.com/jsk-ros-pkg/coral_usb_ros#node-manager-edgetpu_node_managerpy-1

ここにかいてあるんだけど、rosserviceで切り替えられるようにしていた。
```xml
<node name="edgetpu_human_node_manager" pkg="coral_usb" type="edgetpu_node_manager.py">
  <remap from="~input" to="$(arg INPUT_IMAGE)" />
  <rosparam>
    edgetpu_node_manager:
      nodes:
        - name: edgetpu_human_pose_estimator
          type: human_pose_estimator
        - name: edgetpu_panorama_human_pose_estimator
          type: panorama_human_pose_estimator
      default: edgetpu_human_pose_estimator
    edgetpu_human_pose_estimator:
      image_transport: raw
      device_id: 0
    edgetpu_panorama_human_pose_estimator:
      image_transport: raw
      device_id: 0
  </rosparam>
</node>
```

2022-05-27 02:54 UTC, sktometometo commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <arg name="launch_edgetpu_human_pose_estimator" default="true" />
切り替える手間は増えますが (ブラウザを開いてボタンを押す -> ターミナルを開いて rosservice call. 引数は調べる必要あり) インターフェースがあれば僕は十分です。

2022-05-27 05:02 UTC, sktometometo commented
Input imageを変えられる変更がnode managerに必要そうですね。

2022-05-27 05:23 UTC, knorth55 commented
とりあえず現状でマージしてもいいですか？
coralのやつはすこし手間が掛かりそうです．

2022-05-27 05:31 UTC, tkmtnt7000 commented
おそらくこのPRを試すための設定変更の関係上，Fetch1075はfetch15ブランチでネットワーク設定を正しく起動できていない(topicが133系内のPCから見えない)ので関連する部分だけでもマージしていただけると助かります．．．

2022-05-27 05:44 UTC, merged

2022-05-27 06:20 UTC, knorth55 commented
https://github.com/jsk-ros-pkg/coral_usb_ros/pull/101

このcoralのPRがあれば新城くんにいっていたrosserviceでtpuのノードを切り替えることができます．

```
fetch@fetch1075:~$ rosservice call /edgetpu_human_node_manager/list
node_names: 
  - edgetpu_human_pose_estimator
  - edgetpu_panorama_human_pose_estimator
fetch@fetch1075:~$ rosservice call /edgetpu_human_node_manager/start "name: 'edgetpu_panorama_human_pose_estimator'" 
success: True
```