[WIP] add args for what to launch
knorth55/jsk_robot pull request #56
Opened 2020-12-02 06:58 UTC by mqcmd196

To make fetchs' CPU load low, I added args for what nodes to launch.

2020-12-02 07:35 UTC, mqcmd196 commented
When I use this launch file on my demo, the args are below.
```
roslaunch jsk_fetch_startup fetch_bringup.launch battery_warning:=false nav_speak:=false fetch_tweet:=false fetch_sensors:=false use_safe_teleop:=false
```

2020-12-02 10:27 UTC, mqcmd196 commented
The comparison of CPU load

##### `sudo initctl start jsk-fetch-startup`
- rviz
![IMG_4152](https://user-images.githubusercontent.com/27789460/100860576-07974f80-34d4-11eb-98b1-08ae877ecffc.JPG)
- htop
![IMG_4153](https://user-images.githubusercontent.com/27789460/100860657-1e3da680-34d4-11eb-8cfe-e2f0f1268fd0.JPG)

##### `roslaunch jsk_fetch_startup fetch_bringup.launch battery_warning:=false nav_speak:=false fetch_tweet:=false fetch_sensors:=false use_safe_teleop:=false`
- rviz
![IMG_4154](https://user-images.githubusercontent.com/27789460/100860800-5349f900-34d4-11eb-8e06-298a0e8af956.JPG)
- htop
![IMG_4155](https://user-images.githubusercontent.com/27789460/100860813-57761680-34d4-11eb-9fd2-a67621088180.JPG)

2020-12-09 04:09 UTC, mqcmd196 commented
@knorth55 I rebased your branch.

2020-12-09 11:15 UTC, knorth55 requested changes

2020-12-09 11:15 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <node name="imu_corrector" pkg="jsk_fetch_startup" type="imu_corrector.py" if="$(arg imu_corrector)">
these node should not be turned off.

2020-12-09 11:15 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <node name="odom_corrector" pkg="jsk_fetch_startup" type="odom_corrector.py" if="$(arg odom_corrector)">
these node should not be turned off.

2020-12-09 11:15 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +  <include file="$(find jsk_robot_startup)/lifelog/app_manager.launch" if="$(arg app_manager)">
these nodes should not be turned off.

2020-12-09 11:15 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch
> +        args="0 0 0.1 0 0 0 head_pan_link respeaker_base 100" if="$(arg use_speech_recognition)"/>
you can use `group` tag for `use_speech_recognition`
```
<group if="$(arg use_speech_recognition)">
 <node ....
</group>
```

2020-12-10 07:46 UTC, merged